// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwLJ30dUBfUM5cGEz8I290Q_uTxaEqs9k',
    appId: '1:755696294923:web:a1165c6abdea3fc1e23b0e',
    messagingSenderId: '755696294923',
    projectId: 'chat-2023d',
    authDomain: 'chat-2023d.firebaseapp.com',
    storageBucket: 'chat-2023d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRhFBACKqCykCc0EvR93AmTr1tuptzms',
    appId: '1:755696294923:android:e0be3d8868deeec5e23b0e',
    messagingSenderId: '755696294923',
    projectId: 'chat-2023d',
    storageBucket: 'chat-2023d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGJxDWR0NwJdPNX4fT4Jw71Bl5pquX-gw',
    appId: '1:755696294923:ios:6375a11e10b4ebe9e23b0e',
    messagingSenderId: '755696294923',
    projectId: 'chat-2023d',
    storageBucket: 'chat-2023d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGJxDWR0NwJdPNX4fT4Jw71Bl5pquX-gw',
    appId: '1:755696294923:ios:6375a11e10b4ebe9e23b0e',
    messagingSenderId: '755696294923',
    projectId: 'chat-2023d',
    storageBucket: 'chat-2023d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwLJ30dUBfUM5cGEz8I290Q_uTxaEqs9k',
    appId: '1:755696294923:web:2a290483d19a3c37e23b0e',
    messagingSenderId: '755696294923',
    projectId: 'chat-2023d',
    authDomain: 'chat-2023d.firebaseapp.com',
    storageBucket: 'chat-2023d.firebasestorage.app',
  );
}
